// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: spider.proto

package spider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送请求
type SendAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 发送的参数字段
	// 参数类型 参数名 标识号(不可重复)
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // 要请求的地址
	Method  string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`   // 请求方式
}

func (x *SendAddress) Reset() {
	*x = SendAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAddress) ProtoMessage() {}

func (x *SendAddress) ProtoReflect() protoreflect.Message {
	mi := &file_spider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAddress.ProtoReflect.Descriptor instead.
func (*SendAddress) Descriptor() ([]byte, []int) {
	return file_spider_proto_rawDescGZIP(), []int{0}
}

func (x *SendAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SendAddress) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// 返回响应
type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 接收的参数字段
	// 参数类型 参数名 标识号
	HttpCode int32  `protobuf:"varint,1,opt,name=httpCode,proto3" json:"httpCode,omitempty"` // http状态码
	Response string `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`  // 返回体
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_spider_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetHttpCode() int32 {
	if x != nil {
		return x.HttpCode
	}
	return 0
}

func (x *GetResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_spider_proto protoreflect.FileDescriptor

var file_spider_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x22, 0x3f, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x45, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x74, 0x74, 0x70, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x74, 0x74, 0x70, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4a,
	0x0a, 0x08, 0x47, 0x6f, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x13, 0x2e, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x13, 0x2e, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f,
	0x3b, 0x73, 0x70, 0x69, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spider_proto_rawDescOnce sync.Once
	file_spider_proto_rawDescData = file_spider_proto_rawDesc
)

func file_spider_proto_rawDescGZIP() []byte {
	file_spider_proto_rawDescOnce.Do(func() {
		file_spider_proto_rawDescData = protoimpl.X.CompressGZIP(file_spider_proto_rawDescData)
	})
	return file_spider_proto_rawDescData
}

var file_spider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_spider_proto_goTypes = []interface{}{
	(*SendAddress)(nil), // 0: spider.SendAddress
	(*GetResponse)(nil), // 1: spider.GetResponse
}
var file_spider_proto_depIdxs = []int32{
	0, // 0: spider.GoSpider.GetAddressResponse:input_type -> spider.SendAddress
	1, // 1: spider.GoSpider.GetAddressResponse:output_type -> spider.GetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spider_proto_init() }
func file_spider_proto_init() {
	if File_spider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_spider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spider_proto_goTypes,
		DependencyIndexes: file_spider_proto_depIdxs,
		MessageInfos:      file_spider_proto_msgTypes,
	}.Build()
	File_spider_proto = out.File
	file_spider_proto_rawDesc = nil
	file_spider_proto_goTypes = nil
	file_spider_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GoSpiderClient is the client API for GoSpider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoSpiderClient interface {
	// rpc请求 请求的函数 (发送请求参数) returns (返回响应的参数)
	GetAddressResponse(ctx context.Context, in *SendAddress, opts ...grpc.CallOption) (*GetResponse, error)
}

type goSpiderClient struct {
	cc grpc.ClientConnInterface
}

func NewGoSpiderClient(cc grpc.ClientConnInterface) GoSpiderClient {
	return &goSpiderClient{cc}
}

func (c *goSpiderClient) GetAddressResponse(ctx context.Context, in *SendAddress, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/spider.GoSpider/GetAddressResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoSpiderServer is the server API for GoSpider service.
type GoSpiderServer interface {
	// rpc请求 请求的函数 (发送请求参数) returns (返回响应的参数)
	GetAddressResponse(context.Context, *SendAddress) (*GetResponse, error)
}

// UnimplementedGoSpiderServer can be embedded to have forward compatible implementations.
type UnimplementedGoSpiderServer struct {
}

func (*UnimplementedGoSpiderServer) GetAddressResponse(context.Context, *SendAddress) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressResponse not implemented")
}

func RegisterGoSpiderServer(s *grpc.Server, srv GoSpiderServer) {
	s.RegisterService(&_GoSpider_serviceDesc, srv)
}

func _GoSpider_GetAddressResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSpiderServer).GetAddressResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spider.GoSpider/GetAddressResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSpiderServer).GetAddressResponse(ctx, req.(*SendAddress))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoSpider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "spider.GoSpider",
	HandlerType: (*GoSpiderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddressResponse",
			Handler:    _GoSpider_GetAddressResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spider.proto",
}
